version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.handlers.RotatingFileHandler
    filename: logs/application.log
  access:
    formatter: access
    class: logging.handlers.RotatingFileHandler
    filename: logs/access.log
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no