version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  default:
    formatter: default
    class: logging.handlers.RotatingFileHandler
    filename: logs/application.log
    maxBytes: 10000000
    backupCount: 5
  access:
    class: logging.handlers.RotatingFileHandler
    filename: logs/access.log
    maxBytes: 10000000
    backupCount: 5
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
  uvicorn.access:
    handlers:  # no handlers for uvicorn access logs
  access:
    level: INFO
    handlers:
      - access